# Generated by Django 4.2.4 on 2024-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(max_length=2080, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2080)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=2080)),
            ],
        ),
    ]
