# Generated by Django 4.2.4 on 2024-01-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen2', '0002_remove_userdata_id_alter_userdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=2080)),
                ('location', models.CharField(max_length=2080)),
                ('time', models.TimeField()),
                ('file', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
