# Generated by Django 4.2.4 on 2024-01-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen2', '0004_delete_userdata_alter_posts_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(max_length=2080)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=2080)),
            ],
        ),
    ]
